# Generated by Django 2.2 on 2020-04-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksapetable',
            name='user_authority',
            field=models.CharField(choices=[('admin', 'admin'), ('general', 'general')], default='general', max_length=10),
        ),
    ]
