# Generated by Django 2.2 on 2020-04-24 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_worksapetable_user_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksapetable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
