# Generated by Django 3.0.5 on 2020-04-24 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_auto_20200424_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
