# Generated by Django 3.0.5 on 2020-05-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_worksapetable_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksapetable',
            name='user_location',
            field=models.IntegerField(default=0),
        ),
    ]
