# Generated by Django 3.0.5 on 2020-05-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0005_auto_20200523_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksapetable',
            old_name='user_location',
            new_name='user_location_x',
        ),
        migrations.AddField(
            model_name='worksapetable',
            name='user_location_y',
            field=models.IntegerField(default=0),
        ),
    ]
