# Generated by Django 3.0.5 on 2020-05-23 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0006_auto_20200524_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksapetable',
            old_name='user_location_x',
            new_name='user_location',
        ),
        migrations.RemoveField(
            model_name='worksapetable',
            name='user_location_y',
        ),
    ]
