# Generated by Django 3.0.5 on 2020-05-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0007_auto_20200524_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksapetable',
            name='user_location',
            field=models.IntegerField(default=-1),
        ),
    ]
